### ISSUE TITLE
Doesn't compile with retry v0.10.0

### ISSUE THREAD

**Issue by jeffweiss** [jvoegele/external_service#2]
Howdy,
Thank you for `ExternalService`! 

When adding it to a new project, I noticed that it does not compile with the latest version of [`retry`](https://github.com/safwank/ElixirRetry), v0.10.0.

This is the compilation error that I receive:
```
== Compilation error in file lib/external_service.ex ==
** (ArgumentError) invalid syntax, only "retry", "after" and "else" are permitted
    expanding macro: Retry.retry/2
    lib/external_service.ex:299: ExternalService.do_retry/3
    (elixir) lib/kernel/parallel_compiler.ex:198: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/6
```

This problem goes away if I add `{:retry, "~> 0.9.0", override: true}` to my deps.

If I have time this weekend, I'll try to crack at a PR, but until then I figured I ought to open this issue in case other folks stumble across the problem.

**Comment by geofflane** [comment]
:+1:

**Comment by jvoegele** [comment]
Fixed in version `0.8.8` of `external_service`. There are some incompatible changes in `retry` version `0.10.0` so the fix was to specify the version of the dependency as `< 0.10.0`.

**Comment by jeffweiss** [comment]
Thanks for the swift response! 👍
